version: '3'
services:
    apachephp:
        build: ./apachephp
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../www:/var/www/html/
        links:
            - database:mysql

    database:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=camagru
            - MYSQL_ALLOW_EMPTY_PASSWORD=no

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - PMA_PORT=3306
            - PMA_USERNAME=root
            - PMA_PASSWORD=password
            - PMA_ARBITRARY=1
        restart: always
        links:
            - database:mysql

    # mailhog:
    #     image: mailhog/mailhog:v1.0.0
    #     ports:
    #         - "1025:1025"
    #         - "8025:8025"
